services:
  postgres-db:
    image: postgres:15-alpine
    container_name: khu-alquran
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: belajaralquran
      POSTGRES_DB: khu_belajar_quran
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: khu-backend-app
    restart: always
    ports:
      - "5000:5000" # Sesuaikan jika Anda menggunakan port lain
    environment:
      # Koneksi DB mengarah ke container 'postgres-db'
      DATABASE_URL: "postgresql://admin:belajaralquran@postgres-db:5432/khu_belajar_quran?schema=public"
      PORT: 5000
    depends_on:
      - postgres-db

volumes:
  pgdata:
